--- #YAML:1.0
name:               Data-Consumer
version:            0.13
abstract:           Repeatedly consume a data resource in a robust way
author:
    - Yves Orton <YVES@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  0
    DBI:           0
    Fcntl:         0
    File::Path:    2.04
    File::Spec:    3.2701
    POSIX:         0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
